### ISSUE TITLE
添加 secrects的界面没有IP，USERNAME，PASSWORD地方（没有找到和第一张图一样的）

### ISSUE THREAD

**Issue by 413994619** [kkkgo/zerotier-planet-builder#2]
添加 secrects的界面没有IP，USERNAME，PASSWORD地方（没有找到和第一张图一样的），是github改版了吗，大佬。

**Comment by kkkgo** [comment]
那个是要你手动点`New repository secret`按钮，然后添加。

**Comment by kkkgo** [comment]
https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository

**Comment by 413994619** [comment]
大佬，你好，看了上述的URL也没看懂（点了New repository secret后，没有你第一张图的样子，第一张图在下面）
![image](https://github.com/kkkgo/zerotier-planet-builder/assets/137744831/040db300-e7f0-431a-bf29-cbd862b9234d)

请问，是下图这样操作吗，目前我唯一的困扰就是无法修改IP导致搭建出来的控制器客户端无法加入（用户名和密码如果不能修改也罢了，我用ACL控制住WEB权限即可）。
![1688273276501](https://github.com/kkkgo/zerotier-planet-builder/assets/137744831/449eb723-4883-4b20-b336-0acef31de17d)

![image](https://github.com/kkkgo/zerotier-planet-builder/assets/137744831/0435777d-d134-4936-9e80-a28866918347)

**Comment by kkkgo** [comment]
这个是填变量的地方，`Name`一栏你要填变量名字，比如`USERNAME`，`Secret`里面填变量内容，分开逐个添加。

**Comment by kkkgo** [comment]
![image](https://github.com/kkkgo/zerotier-planet-builder/assets/4530897/c8efd3d2-b159-4899-8ac2-bf579bcd3043)

**Comment by 413994619** [comment]
感谢大佬的耐心解答，是我才菜了，三个分别添加后，如下图，这样应该没问题了，我下午正式搭建一下试试，有问题再来叨扰。
![image](https://github.com/kkkgo/zerotier-planet-builder/assets/137744831/06b9dfdc-8680-4cb7-ae01-f925c6d5ab28)
